# Use a local container set up like this:
# https://github.com/TurbulentDynamics/TD-env-setup-dev-help/env-setup/nvidia-docker2-base-ml-container.md
FROM td_base_ml

RUN sudo apt install ffmpeg
RUN pip install -U --user librosa tqdm pyyaml 
